[package]
name = "styled-components"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
once_cell = "1.12.1"
proc-macro2 = "1.0.40"
syn = "1.0.98"
quote = "1.0.20"
web-sys = { version = "0.3.58", features = ["Document", "Window", "Element", "HtmlHeadElement"] }
